# -*- coding: utf-8 -*-
"""Premium Thai Restuarant Intelligent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUx6LfLXoKmujPedXNTlnKMF2kUD8HLE
"""

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime, time
import altair as alt

# Enhanced mock customer database with Thai names
def create_mock_customer_data():
    customers = {
        'คุณสมชาย วงศ์พัฒนา': {
            'visits': 15,
            'favorite_dishes': {
                'lunch': ['ผัดกะเพราหมูกรอบ', 'ต้มยำกุ้ง', 'ส้มตำไทย'],
                'dinner': ['ปลากะพงนึ่งมะนาว', 'แกงเผ็ดเป็ดย่าง', 'กุ้งแม่น้ำเผา']
            },
            'preferences': ['เผ็ดน้อย', 'ไม่ใส่ผงชูรส'],
            'allergies': ['กุ้ง'],
            'avg_spend': 2500,
            'last_visit': '2025-02-01',
            'typical_group_size': 2,
            'preferred_categories': {
                'lunch': ['อาหารจานเดียว', 'ส้มตำ'],
                'dinner': ['อาหารทะเล', 'แกง', 'เครื่องดื่ม']
            },
            'past_orders': [
                {'date': '2025-02-01', 'time': '19:30', 'items': ['ปลากะพงนึ่งมะนาว', 'ไวน์ขาว'], 'group_size': 2},
                {'date': '2025-01-15', 'time': '12:30', 'items': ['ผัดกะเพราหมูกรอบ', 'ส้มตำไทย'], 'group_size': 1},
            ]
        },
        'ครอบครัวคุณวิภา สุขสวัสดิ์': {
            'visits': 8,
            'favorite_dishes': {
                'lunch': ['ผัดไทยกุ้งสด', 'ยำวุ้นเส้น', 'ข้าวผัดปู'],
                'dinner': ['ต้มยำกุ้งน้ำข้น', 'ปลากะพงทอดน้ำปลา', 'มัสมั่นเนื้อ']
            },
            'preferences': ['รสจัด', 'ชอบอาหารทะเล'],
            'allergies': ['ถั่ว'],
            'avg_spend': 4500,
            'last_visit': '2025-02-10',
            'typical_group_size': 4,
            'preferred_categories': {
                'lunch': ['อาหารจานเดียว', 'ยำ', 'เมนูเด็ก'],
                'dinner': ['อาหารทะเล', 'แกง', 'ของหวาน']
            },
            'past_orders': [
                {'date': '2025-02-10', 'time': '18:00', 'items': ['ต้มยำกุ้งน้ำข้น', 'ข้าวผัดหมูสำหรับเด็ก', 'ไอศกรีมกะทิ'], 'group_size': 4},
                {'date': '2025-01-28', 'time': '13:00', 'items': ['ผัดไทยกุ้งสด', 'ยำวุ้นเส้น', 'น้ำมะพร้าว'], 'group_size': 4},
            ]
        }
    }
    return customers

def create_mock_menu():
    return {
        'อาหารว่าง': {
            'items': ['ทอดมันกุ้ง', 'ปอเปี๊ยะทอด', 'ขนมจีบกุ้ง', 'สะเต๊ะไก่'],
            'available': ['lunch', 'dinner']
        },
        'ยำ & สลัด': {
            'items': ['ส้มตำไทย', 'ยำวุ้นเส้น', 'ลาบทอด', 'พล่ากุ้ง'],
            'available': ['lunch', 'dinner']
        },
        'อาหารจานเดียว': {
            'items': ['ผัดกะเพราหมูกรอบ', 'ผัดไทยกุ้งสด', 'ข้าวผัดปู', 'ราดหน้าทะเล'],
            'available': ['lunch']
        },
        'แกง': {
            'items': ['แกงเผ็ดเป็ดย่าง', 'มัสมั่นเนื้อ', 'แกงส้มชะอมกุ้ง', 'พะแนงไก่'],
            'available': ['dinner']
        },
        'อาหารทะเล': {
            'items': ['ปลากะพงนึ่งมะนาว', 'กุ้งแม่น้ำเผา', 'ปูนิ่มผัดผงกะหรี่', 'หอยเชลล์เผา'],
            'available': ['dinner']
        },
        'ของหวาน': {
            'items': ['ข้าวเหนียวมะม่วง', 'ทับทิมกรอบ', 'บัวลอย', 'ไอศกรีมกะทิ'],
            'available': ['lunch', 'dinner']
        }
    }

def get_current_service(current_time=None):
    if not current_time:
        current_time = datetime.now().time()
    lunch_start = time(11, 0)
    lunch_end = time(16, 0)
    return 'lunch' if lunch_start <= current_time <= lunch_end else 'dinner'

def get_recommendations(customer_data, menu, current_service, group_size):
    recommendations = {
        'must_try': [],
        'based_on_history': [],
        'group_special': []
    }

    # Filter menu items based on current service time
    available_items = []
    for category, details in menu.items():
        if current_service in details['available']:
            available_items.extend(details['items'])

    # Get customer preferences for current service
    preferred_categories = customer_data['preferred_categories'].get(current_service, [])

    # Must-try recommendations based on preferred categories
    for category in preferred_categories:
        if category in menu and current_service in menu[category]['available']:
            recommendations['must_try'].extend(
                [item for item in menu[category]['items']
                 if item not in [order['items'] for order in customer_data['past_orders']]][:2]
            )

    # Group-based recommendations
    if group_size >= 4:
        recommendations['group_special'] = [
            'ชุดสำรับครอบครัว',
            'ชุดอาหารว่างรวม',
            'ชุดของหวานรวม'
        ]
    elif group_size == 2:
        recommendations['group_special'] = [
            'ชุดคู่รัก',
            'ชุดของหวานคู่',
            'ชุดไวน์พิเศษ'
        ]

    return recommendations

def main():
    st.set_page_config(page_title="ครัวไทยพรีเมียม - ระบบข้อมูลลูกค้า", layout="wide")

    # Initialize session state
    if 'customers' not in st.session_state:
        st.session_state.customers = create_mock_customer_data()
    if 'menu' not in st.session_state:
        st.session_state.menu = create_mock_menu()

    st.title("ครัวไทยพรีเมียม")
    st.subheader("ระบบข้อมูลลูกค้า")

    # Current service time
    current_service = get_current_service()
    st.info(f"บริการปัจจุบัน: {current_service.upper()}")

    # Customer search
    customer_name = st.selectbox(
        "เลือกลูกค้า:",
        options=list(st.session_state.customers.keys())
    )

    if customer_name:
        customer = st.session_state.customers[customer_name]

        # Group size selection
        group_size = st.number_input(
            "จำนวนลูกค้า:",
            min_value=1,
            max_value=12,
            value=customer['typical_group_size']
        )

        col1, col2 = st.columns(2)

        with col1:
            st.header("ข้อมูลลูกค้า")
            st.write(f"จำนวนครั้งที่มาใช้บริการ: {customer['visits']}")
            st.write(f"ค่าใช้จ่ายเฉลี่ย: {customer['avg_spend']} บาท")
            st.write(f"จำนวนลูกค้าทั่วไป: {customer['typical_group_size']}")
            st.write(f"มาใช้บริการครั้งล่าสุด: {customer['last_visit']}")

            st.subheader("ข้อควรระวังและความชอบ")
            for pref in customer['preferences']:
                st.info(pref)
            for allergy in customer['allergies']:
                st.warning(f"⚠️ แพ้: {allergy}")

        with col2:
            st.header("คำแนะนำเมนู")
            recommendations = get_recommendations(customer, st.session_state.menu, current_service, group_size)

            st.subheader("🌟 แนะนำ")
            for item in recommendations['must_try']:
                st.success(item)

            st.subheader("👥 เหมาะสำหรับกลุ่ม")
            for item in recommendations['group_special']:
                st.info(item)

        # Order History
        st.header("ประวัติการสั่งอาหาร")
        history_df = pd.DataFrame([
            {
                'วันที่': order['date'],
                'เวลา': order['time'],
                'รายการ': ', '.join(order['items']),
                'จำนวนลูกค้า': order['group_size']
            }
            for order in customer['past_orders']
        ])
        st.dataframe(history_df)

        # New Order Section
        st.header("สั่งอาหารใหม่")

        available_categories = [
            category for category, details in st.session_state.menu.items()
            if current_service in details['available']
        ]

        selected_category = st.selectbox(
            "เลือกประเภทอาหาร",
            options=available_categories
        )

        if selected_category:
            selected_items = st.multiselect(
                "เลือกรายการอาหาร",
                options=st.session_state.menu[selected_category]['items']
            )

            if st.button("เพิ่มรายการ"):
                new_order = {
                    'date': datetime.now().strftime('%Y-%m-%d'),
                    'time': datetime.now().strftime('%H:%M'),
                    'items': selected_items,
                    'group_size': group_size
                }
                customer['past_orders'].insert(0, new_order)
                st.success("เพิ่มรายการสำเร็จ!")
                st.experimental_rerun()

if __name__ == "__main__":
    main()