# -*- coding: utf-8 -*-
"""The premium adjust UX UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W02oMgSQ3z2Rr58jpxvohb_vx2QD6IJf
"""

import streamlit as st
import pandas as pd
from datetime import datetime, time
from collections import Counter

st.set_page_config(
    page_title="ครัวไทยพรีเมียม",
    page_icon="🍜",
    layout="wide"
)

def get_mock_customers():
    return {
        'คุณสมชาย วงศ์พัฒนา': {
            'visits': 15,
            'preferences': ['เผ็ดน้อย', 'ไม่ใส่ผงชูรส'],
            'allergies': ['กุ้ง'],
            'avg_spend': 2500,
            'last_visit': '2025-02-01',
            'past_orders': [
                {'date': '2025-02-01', 'meal_time': 'dinner', 'items': ['ปลากะพงนึ่งมะนาว', 'ผัดผักบุ้งไฟแดง', 'ต้มข่าไก่']},
                {'date': '2025-01-15', 'meal_time': 'lunch', 'items': ['ผัดกะเพราหมูกรอบ', 'ต้มยำกุ้ง', 'ส้มตำไทย']},
                {'date': '2025-01-10', 'meal_time': 'dinner', 'items': ['แกงเผ็ดเป็ดย่าง', 'ผัดผักรวม', 'ต้มข่าไก่']}
            ]
        },
        'ครอบครัวคุณวิภา สุขสวัสดิ์': {
            'visits': 8,
            'preferences': ['รสจัด', 'ชอบอาหารทะเล'],
            'allergies': ['ถั่ว'],
            'avg_spend': 4500,
            'last_visit': '2025-02-10',
            'past_orders': [
                {'date': '2025-02-10', 'meal_time': 'dinner', 'items': ['ต้มยำกุ้งน้ำข้น', 'ปลากะพงทอดน้ำปลา', 'ผัดผักรวมมิตร']},
                {'date': '2025-01-28', 'meal_time': 'lunch', 'items': ['ผัดไทยกุ้งสด', 'ยำวุ้นเส้น', 'ไข่เจียวปู']},
                {'date': '2025-01-20', 'meal_time': 'dinner', 'items': ['มัสมั่นเนื้อ', 'ผัดผักบุ้ง', 'ต้มข่าไก่']}
            ]
        }
    }

def get_menu_by_meal_time():
    return {
        'lunch': {
            'อาหารจานเดียว': [
                'ผัดกะเพราหมูกรอบ',
                'ผัดไทยกุ้งสด',
                'ข้าวผัดปู',
                'ไข่เจียวปู'
            ],
            'ต้มและแกง': [
                'ต้มยำกุ้ง',
                'ต้มข่าไก่',
                'แกงจืดเต้าหู้',
                'ต้มซุปไก่'
            ],
            'ผัดผัก': [
                'ผัดผักบุ้งไฟแดง',
                'ผัดผักรวมมิตร',
                'ผัดคะน้าหมูกรอบ'
            ]
        },
        'dinner': {
            'อาหารทะเล': [
                'ปลากะพงนึ่งมะนาว',
                'กุ้งแม่น้ำเผา',
                'ปลากะพงทอดน้ำปลา',
                'ปูนิ่มผัดผงกะหรี่'
            ],
            'แกงและต้มยำ': [
                'ต้มยำกุ้งน้ำข้น',
                'แกงเผ็ดเป็ดย่าง',
                'มัสมั่นเนื้อ',
                'แกงส้มชะอมกุ้ง'
            ],
            'ผัดและทอด': [
                'ผัดผักบุ้งไฟแดง',
                'ผัดผักรวมมิตร',
                'ผัดเผ็ดปลาดุก',
                'ปลาทอดสามรส'
            ]
        }
    }

def analyze_order_history(customer, meal_time):
    # Filter orders by meal time
    relevant_orders = [order for order in customer['past_orders']
                      if order['meal_time'] == meal_time]

    # Count item frequencies
    all_items = [item for order in relevant_orders for item in order['items']]
    item_counts = Counter(all_items)

    # Get most common items
    most_common = item_counts.most_common(3)

    # Get categories they prefer
    menu = get_menu_by_meal_time()[meal_time]
    category_counts = Counter()

    for item in all_items:
        for category, items in menu.items():
            if item in items:
                category_counts[category] += 1

    preferred_categories = category_counts.most_common(2)

    return most_common, preferred_categories

def get_recommendations(customer, meal_time, menu):
    most_common_items, preferred_categories = analyze_order_history(customer, meal_time)

    recommendations = {
        'favorites': [item[0] for item in most_common_items],
        'new_suggestions': []
    }

    # Get new suggestions from their preferred categories
    for category, _ in preferred_categories:
        category_items = menu[meal_time][category]
        new_items = [item for item in category_items
                    if item not in recommendations['favorites']
                    and item not in [i for order in customer['past_orders']
                                   for i in order['items']]]
        recommendations['new_suggestions'].extend(new_items[:2])

    return recommendations

def main():
    if 'customers' not in st.session_state:
        st.session_state.customers = get_mock_customers()
    if 'menu' not in st.session_state:
        st.session_state.menu = get_menu_by_meal_time()

    st.title("🍜 ครัวไทยพรีเมียม")
    st.subheader("ระบบแนะนำอาหารและประวัติลูกค้า")

    # First box - Meal time selection
    col1, col2 = st.columns([1, 2])
    with col1:
        meal_time = st.radio(
            "กรุณาเลือกมื้ออาหาร",
            options=['lunch', 'dinner'],
            format_func=lambda x: "มื้อกลางวัน" if x == 'lunch' else "มื้อเย็น"
        )

    # Customer selection
    customer_name = st.selectbox(
        "เลือกลูกค้า",
        options=list(st.session_state.customers.keys())
    )

    if customer_name and meal_time:
        customer = st.session_state.customers[customer_name]

        # Order History and Recommendations Section
        st.markdown(f"### ประวัติการสั่งอาหารและคำแนะนำสำหรับ{meal_time}")

        # Display last 3 orders
        history_df = pd.DataFrame([
            {
                'วันที่': order['date'],
                'มื้ออาหาร': 'กลางวัน' if order['meal_time'] == 'lunch' else 'เย็น',
                'รายการอาหาร': ', '.join(order['items'])
            }
            for order in customer['past_orders'][:3]  # Show only last 3 orders
        ])
        st.dataframe(history_df, use_container_width=True)

        # Get and display recommendations
        recommendations = get_recommendations(customer, meal_time, st.session_state.menu)

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### 🌟 เมนูที่สั่งประจำ")
            for item in recommendations['favorites']:
                st.success(f"• {item}")

        with col2:
            st.markdown("### 🆕 เมนูแนะนำใหม่")
            for item in recommendations['new_suggestions']:
                st.info(f"• {item}")

        # Customer Details Section
        st.markdown("### ข้อมูลลูกค้า")
        col1, col2 = st.columns(2)

        with col1:
            st.write(f"จำนวนครั้งที่มาใช้บริการ: {customer['visits']}")
            st.write(f"ค่าใช้จ่ายเฉลี่ย: {customer['avg_spend']} บาท")

        with col2:
            for pref in customer['preferences']:
                st.info(f"🔵 {pref}")
            for allergy in customer['allergies']:
                st.warning(f"⚠️ แพ้: {allergy}")

        # New Order Section
        st.markdown("### สั่งอาหารใหม่")
        category = st.selectbox(
            "เลือกประเภทอาหาร",
            options=list(st.session_state.menu[meal_time].keys())
        )

        if category:
            selected_items = st.multiselect(
                "เลือกรายการอาหาร",
                options=st.session_state.menu[meal_time][category]
            )

            if st.button("บันทึกรายการ"):
                new_order = {
                    'date': datetime.now().strftime('%Y-%m-%d'),
                    'meal_time': meal_time,
                    'items': selected_items
                }
                customer['past_orders'].insert(0, new_order)
                st.success("บันทึกรายการสำเร็จ")
                st.write("รายการที่สั่ง:", ', '.join(selected_items))

if __name__ == "__main__":
    main()